pointcloud_to_laserscan:
  ros__parameters:
    target_frame: "livox_frame"
    transform_tolerance: 0.1
    min_height: -2.0
    max_height: 0.2
    range_min: 1.0
    angle_increment: 0.0174533
    scan_time: 0.1
    range_max: 40.0
    use_inf: true
    inf_epsilon: 1.0
