controller_manager:
  ros__parameters:
    update_rate: 50
    # we're not on a real-time system
    lock_memory: False
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController
joint_state_broadcaster:
  ros__parameters:
    map_interface_to_joint_state:
      effort: current
diff_drive_base_controller:
  ros__parameters:
    # Hardware configuration
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    wheel_separation: 0.714
    wheels_per_side: 2
    wheel_radius: 0.147
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    open_loop: false
    # ROS I/O configuration
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: false # Disabled - using EKF for odometry transforms
    cmd_vel_timeout: 1.0
    #publish_limited_velocity: true
    use_stamped_vel: true

    # Kinematic limits
    # If min_* is not specified, defaults to -max_*
    linear.x.max_velocity: 1.7
    linear.x.max_acceleration: 10.0
    linear.x.max_jerk: .NAN
    angular.z.max_velocity: 5.0
    angular.z.max_acceleration: 10.0
    angular.z.max_jerk: .NAN
