waypoints:
  - {x: 1.0, y: 2.0, theta: 0.0}
  - {x: 1.0, y: 0.5, theta: 1.57}
  - {x: 0.0, y: 2.0, theta: 3.14}
  - {x: 2.0, y: 1.0, theta: -1.57}
  - {x: 0.0, y: 0.0, theta: 0.0} # Return to origin
  - {x: 1.0, y: 2.0, theta: 0.0}
  - {x: 1.0, y: 0.5, theta: 1.57}
  - {x: 0.0, y: 2.0, theta: 3.14}
  - {x: 2.0, y: 1.0, theta: -1.57}
  - {x: 0.0, y: 0.0, theta: 0.0} # Return to origin
  - {x: 1.0, y: 2.0, theta: 0.0}
  - {x: 1.0, y: 0.5, theta: 1.57}
  - {x: 0.0, y: 2.0, theta: 3.14}
  - {x: 2.0, y: 1.0, theta: -1.57}
  - {x: 0.0, y: 0.0, theta: 0.0} # Return to origin
  - {x: 1.0, y: 2.0, theta: 0.0}
  - {x: 1.0, y: 0.5, theta: 1.57}
  - {x: 0.0, y: 2.0, theta: 3.14}
  - {x: 2.0, y: 1.0, theta: -1.57}
  - {x: 0.0, y: 0.0, theta: 0.0} # Return to origin
