aruco_detector:
  ros__parameters:
    use_sim_time: true
    camera_matrix: [530.4, 0.0, 320.0, 0.0, 530.4, 240.0, 0.0, 0.0, 1.0] # fx, 0, cx, 0, fy, cy, 0, 0, 1
    distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]
    dictionary_id: 1 # 4x4: 50=0, 100=1, 250=2, 1000=3 | 5x5: 50=4, 100=5, 250=6, 1000=7 | 6x6: 50=8, 100=9, 250=10, 1000=11
    marker_length: 0.35 # in meters
    axis_length: 0.03 # in meters
    camera_frame: "camera_link_optical" # input frame of the camera
    publish_tf: true # whether to transform to output frame
    tf_output_frame: "odom" # reference frame for published TFs
    compressed_io: false # Enable if input/output images are compressed
    # If compressed_input_output is true, the system assumes that the input image is a compressed image.
    input_img: "/rgbd_camera/image_raw"
    publish_img: false  # disable publishing of output image
    output_img: "/detection/aruco/image_raw"
    publish_output: true
    output_topic: "/detection/aruco"


cube_detector:
  ros__parameters:
    use_sim_time: true
    model_path: /model/best.onnx
    map_ID: ["green", "red", "blue", "white"]  # List of cube colors to detect and map with the model's class IDs
    use_cuda: true # set to false - CPU inference is well-optimized with multi-threading
    confidence_threshold: 0.29
    nms_threshold: 0.5 # IoU threshold for Non-Max Suppression
    cube_distance_threshold: 1.0  # meters
    min_detections_for_stable: 1
    camera_matrix: [530.4, 0.0, 320.0, 0.0, 530.4, 240.0, 0.0, 0.0, 1.0] # fx, 0, cx, 0, fy, cy, 0, 0, 1
    camera_frame: "camera_link_optical" # input frame of the camera
    publish_tf: true # whether to transform to output frame
    tf_output_frame: "odom" # reference frame for published TFs
    compressed_io: false # Enable if input/output images are compressed
    # If compressed_input_output is true, the system assumes that the input image is a compressed image.
    input_img: "/rgbd_camera/image_raw"
    publish_img: true
    output_img: "/detection/cube/image_raw"
    publish_output: true
    output_topic: "/detection/cube"
