aruco_detector:
  ros__parameters:
    camera_matrix: [530.4, 0.0, 320.0,
                    0.0, 530.4, 240.0,
                    0.0, 0.0, 1.0]

    distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]

    marker_length: 0.35
    axis_length: 0.03

    camera_frame: "camera_link_optical"
    tf_output_frame: "odom"

    input_topic: "/rgbd_camera/image_raw"
    output_topic: "/detection/aruco/image"
