/camera/camera:
  ros__parameters:

    ############################
    # Device & General
    ############################
    camera_name: camera
    camera_namespace: camera

    serial_no: ""
    usb_port_id: ""
    device_type: ""

    initial_reset: false
    accelerate_gpu_with_glsl: false

    json_file_path: ""
    rosbag_filename: ""
    rosbag_loop: false

    log_level: info
    output: screen

    ############################
    # Stream Enable Flags
    ############################
    enable_color: false
    enable_depth: true

    enable_infra: false
    enable_infra1: false
    enable_infra2: false

    enable_sync: false
    enable_rgbd: false

    ############################
    # Color Camera
    ############################
    rgb_camera.color_profile: "0,0,0"
    rgb_camera.color_format: RGB8
    rgb_camera.enable_auto_exposure: true

    ############################
    # Depth Module
    ############################
    depth_module.depth_profile: "0,0,0"
    depth_module.depth_format: Z16

    depth_module.infra_profile: "0,0,0"
    depth_module.infra_format: RGB8
    depth_module.infra1_format: Y8
    depth_module.infra2_format: Y8

    depth_module.color_profile: "0,0,0"
    depth_module.color_format: RGB8

    depth_module.enable_auto_exposure: true
    depth_module.exposure: 8500
    depth_module.gain: 16

    # HDR (usually OFF)
    depth_module.hdr_enabled: false
    depth_module.exposure.1: 7500
    depth_module.gain.1: 16
    depth_module.exposure.2: 1
    depth_module.gain.2: 16

    depth_module.inter_cam_sync_mode: 0  # 0=Default, 1=Master, 2=Slave

    ############################
    # IMU (D435i / D455)
    ############################
    enable_gyro: true
    enable_accel: true
    enable_motion: false

    gyro_fps: 0
    accel_fps: 0

    unite_imu_method: 2   # 0=None, 1=copy, 2=linear_interpolation

    angular_velocity_cov: 0.01
    linear_accel_cov: 0.01

    ############################
    # PointCloud
    ############################
    pointcloud.enable: true
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: 0
    pointcloud.ordered_pc: false
    pointcloud.allow_no_texture_points: false

    ############################
    # Filters
    ############################
    align_depth.enable: false
    colorizer.enable: false
    decimation_filter.enable: false
    rotation_filter.enable: false
    rotation_filter.rotation: 0.0
    spatial_filter.enable: false
    temporal_filter.enable: false
    disparity_filter.enable: false
    hole_filling_filter.enable: false
    hdr_merge.enable: false

    ############################
    # TF & Frames
    ############################
    publish_tf: true
    tf_publish_rate: 0.0
    base_frame_id: link

    ############################
    # Misc
    ############################
    clip_distance: -2.0
    diagnostics_period: 0.0

    wait_for_device_timeout: -1.0
    reconnect_timeout: 6.0
